name: 'StartMenuCleaner-CI'

on:
    push:
      branches:
        - main

jobs:
  build:
    name: 'Build StartMenuCleaner'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300
          source-url: ${{ secrets.GPR_URI }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.GITHUB_TOKEN }}
          nuget-version: 'latest'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Upload output artifact
        uses: actions/upload-artifact@v2
        with:
          name: __output
          path: __output
      - name: Upload packages artifact
        uses: actions/upload-artifact@v2
        with:
          name: __packages
          path: __packages
      - name: Configure NuGet.config
        run: nuget sources add -Name 'github' -Source ${{ secrets.GPR_URI }} -UserName ${{ secrets.GPR_USERNAME }} -Password ${{ secrets.GITHUB_TOKEN }}
      - name: Publish NuGet package to GitHub registry
        run: dotnet nuget push ./__packages/NuGet/Release/*.nupkg --skip-duplicate --source 'github'