name: Release Workflow

on:
  workflow_call:
    inputs:
      package-version:
        type: string
        required: true

jobs:
  release:
    name: Release
    runs-on: windows-latest
    environment:
      name: NuGet.org
      url: https://www.nuget.org

    steps:
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1
        with:
          nuget-version: latest

      - name: Download packages artifact
        uses: actions/download-artifact@v3
        with:
          name: packages
          path: __artifacts/package

      - name: Configure GitHub NuGet registry
        run: nuget sources add -name github -source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -username ${{ github.repository_owner }} -password ${{ secrets.GITHUB_TOKEN }}

      - name: Push ${{ inputs.package-version }} to GitHub package registry
        run: nuget push __artifacts/package/release/*.nupkg -ApiKey ${{ secrets.GITHUB_TOKEN }} -Source github
